import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const PAPECODE_EXPERIMENTAL = truthy("PAPECODE_EXPERIMENTAL")
const PAPECODE_DISABLE_CLAUDE_CODE = truthy("PAPECODE_DISABLE_CLAUDE_CODE")
const PAPECODE_DISABLE_CLAUDE_CODE_SKILLS =
  PAPECODE_DISABLE_CLAUDE_CODE || truthy("PAPECODE_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["PAPECODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  PAPECODE_AUTO_SHARE: truthy("PAPECODE_AUTO_SHARE"),
  PAPECODE_AUTO_HEAP_SNAPSHOT: truthy("PAPECODE_AUTO_HEAP_SNAPSHOT"),
  PAPECODE_GIT_BASH_PATH: process.env["PAPECODE_GIT_BASH_PATH"],
  PAPECODE_CONFIG: process.env["PAPECODE_CONFIG"],
  PAPECODE_CONFIG_CONTENT: process.env["PAPECODE_CONFIG_CONTENT"],
  PAPECODE_DISABLE_AUTOUPDATE: truthy("PAPECODE_DISABLE_AUTOUPDATE"),
  PAPECODE_ALWAYS_NOTIFY_UPDATE: truthy("PAPECODE_ALWAYS_NOTIFY_UPDATE"),
  PAPECODE_DISABLE_PRUNE: truthy("PAPECODE_DISABLE_PRUNE"),
  PAPECODE_DISABLE_TERMINAL_TITLE: truthy("PAPECODE_DISABLE_TERMINAL_TITLE"),
  PAPECODE_SHOW_TTFD: truthy("PAPECODE_SHOW_TTFD"),
  PAPECODE_PERMISSION: process.env["PAPECODE_PERMISSION"],
  PAPECODE_DISABLE_DEFAULT_PLUGINS: truthy("PAPECODE_DISABLE_DEFAULT_PLUGINS"),
  PAPECODE_DISABLE_LSP_DOWNLOAD: truthy("PAPECODE_DISABLE_LSP_DOWNLOAD"),
  PAPECODE_ENABLE_EXPERIMENTAL_MODELS: truthy("PAPECODE_ENABLE_EXPERIMENTAL_MODELS"),
  PAPECODE_DISABLE_AUTOCOMPACT: truthy("PAPECODE_DISABLE_AUTOCOMPACT"),
  PAPECODE_DISABLE_MODELS_FETCH: truthy("PAPECODE_DISABLE_MODELS_FETCH"),
  PAPECODE_DISABLE_MOUSE: truthy("PAPECODE_DISABLE_MOUSE"),
  PAPECODE_DISABLE_CLAUDE_CODE,
  PAPECODE_DISABLE_CLAUDE_CODE_PROMPT: PAPECODE_DISABLE_CLAUDE_CODE || truthy("PAPECODE_DISABLE_CLAUDE_CODE_PROMPT"),
  PAPECODE_DISABLE_CLAUDE_CODE_SKILLS,
  PAPECODE_DISABLE_EXTERNAL_SKILLS: PAPECODE_DISABLE_CLAUDE_CODE_SKILLS || truthy("PAPECODE_DISABLE_EXTERNAL_SKILLS"),
  PAPECODE_FAKE_VCS: process.env["PAPECODE_FAKE_VCS"],
  PAPECODE_SERVER_PASSWORD: process.env["PAPECODE_SERVER_PASSWORD"],
  PAPECODE_SERVER_USERNAME: process.env["PAPECODE_SERVER_USERNAME"],
  PAPECODE_ENABLE_QUESTION_TOOL: truthy("PAPECODE_ENABLE_QUESTION_TOOL"),

  // Experimental
  PAPECODE_EXPERIMENTAL,
  PAPECODE_EXPERIMENTAL_FILEWATCHER: Config.boolean("PAPECODE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  PAPECODE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("PAPECODE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  PAPECODE_EXPERIMENTAL_ICON_DISCOVERY: PAPECODE_EXPERIMENTAL || truthy("PAPECODE_EXPERIMENTAL_ICON_DISCOVERY"),
  PAPECODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("PAPECODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  PAPECODE_ENABLE_EXA: truthy("PAPECODE_ENABLE_EXA") || PAPECODE_EXPERIMENTAL || truthy("PAPECODE_EXPERIMENTAL_EXA"),
  PAPECODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("PAPECODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  PAPECODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("PAPECODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  PAPECODE_EXPERIMENTAL_OXFMT: PAPECODE_EXPERIMENTAL || truthy("PAPECODE_EXPERIMENTAL_OXFMT"),
  PAPECODE_EXPERIMENTAL_LSP_TY: truthy("PAPECODE_EXPERIMENTAL_LSP_TY"),
  PAPECODE_EXPERIMENTAL_LSP_TOOL: PAPECODE_EXPERIMENTAL || truthy("PAPECODE_EXPERIMENTAL_LSP_TOOL"),
  PAPECODE_EXPERIMENTAL_PLAN_MODE: PAPECODE_EXPERIMENTAL || truthy("PAPECODE_EXPERIMENTAL_PLAN_MODE"),
  PAPECODE_EXPERIMENTAL_MARKDOWN: !falsy("PAPECODE_EXPERIMENTAL_MARKDOWN"),
  PAPECODE_MODELS_URL: process.env["PAPECODE_MODELS_URL"],
  PAPECODE_MODELS_PATH: process.env["PAPECODE_MODELS_PATH"],
  PAPECODE_DISABLE_EMBEDDED_WEB_UI: truthy("PAPECODE_DISABLE_EMBEDDED_WEB_UI"),
  PAPECODE_DB: process.env["PAPECODE_DB"],
  PAPECODE_DISABLE_CHANNEL_DB: truthy("PAPECODE_DISABLE_CHANNEL_DB"),
  PAPECODE_SKIP_MIGRATIONS: truthy("PAPECODE_SKIP_MIGRATIONS"),
  PAPECODE_STRICT_CONFIG_DEPS: truthy("PAPECODE_STRICT_CONFIG_DEPS"),

  PAPECODE_WORKSPACE_ID: process.env["PAPECODE_WORKSPACE_ID"],
  PAPECODE_EXPERIMENTAL_HTTPAPI: truthy("PAPECODE_EXPERIMENTAL_HTTPAPI"),
  PAPECODE_EXPERIMENTAL_WORKSPACES: PAPECODE_EXPERIMENTAL || truthy("PAPECODE_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get PAPECODE_DISABLE_PROJECT_CONFIG() {
    return truthy("PAPECODE_DISABLE_PROJECT_CONFIG")
  },
  get PAPECODE_TUI_CONFIG() {
    return process.env["PAPECODE_TUI_CONFIG"]
  },
  get PAPECODE_CONFIG_DIR() {
    return process.env["PAPECODE_CONFIG_DIR"]
  },
  get PAPECODE_PURE() {
    return truthy("PAPECODE_PURE")
  },
  get PAPECODE_PLUGIN_META_FILE() {
    return process.env["PAPECODE_PLUGIN_META_FILE"]
  },
  get PAPECODE_CLIENT() {
    return process.env["PAPECODE_CLIENT"] ?? "cli"
  },
}
