id = "papecode"
name = "PapeCode"
description = "The open source coding agent."
version = "1.14.24"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/anomalyco/papecode"

[agent_servers.papecode]
name = "PapeCode"
icon = "./icons/papecode.svg"

[agent_servers.papecode.targets.darwin-aarch64]
archive = "https://github.com/anomalyco/papecode/releases/download/v1.14.24/papecode-darwin-arm64.zip"
cmd = "./papecode"
args = ["acp"]

[agent_servers.papecode.targets.darwin-x86_64]
archive = "https://github.com/anomalyco/papecode/releases/download/v1.14.24/papecode-darwin-x64.zip"
cmd = "./papecode"
args = ["acp"]

[agent_servers.papecode.targets.linux-aarch64]
archive = "https://github.com/anomalyco/papecode/releases/download/v1.14.24/papecode-linux-arm64.tar.gz"
cmd = "./papecode"
args = ["acp"]

[agent_servers.papecode.targets.linux-x86_64]
archive = "https://github.com/anomalyco/papecode/releases/download/v1.14.24/papecode-linux-x64.tar.gz"
cmd = "./papecode"
args = ["acp"]

[agent_servers.papecode.targets.windows-x86_64]
archive = "https://github.com/anomalyco/papecode/releases/download/v1.14.24/papecode-windows-x64.zip"
cmd = "./papecode.exe"
args = ["acp"]
