name: papecode

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  papecode:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /papecode') ||
      startsWith(github.event.comment.body, '/papecode')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run papecode
        uses: anomalyco/papecode/github@latest
        env:
          PAPECODE_API_KEY: ${{ secrets.PAPECODE_API_KEY }}
          PAPECODE_PERMISSION: '{"bash": "deny"}'
        with:
          model: papecode/claude-opus-4-5
